---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:7
    #image: quay.io/centos/centos:stream8
    pre_build_image: true
    command: /sbin/init
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
